name: Trigger Jenkins Job

on:
  repository_dispatch:
    types: [testrail_trigger]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins
        env:
          JENKINS_URL: "http://3.16.66.131:18081/view/TestRailDemo/job/Demo%20Mock%20Application%20Build%20Job/build"
          JENKINS_BASIC: ${{ secrets.JENKINS_BASIC }}
        run: |
          set -e
          curl -sS -X POST "$JENKINS_URL" -u "$JENKINS_BASIC"
